---

- name: Install Pebble for Let's Encrypt
  hosts: '*pebble*'

  vars:
    pebble_version: 'v2.3.1'
  tasks:
    - name: Install pebble
      get_url:
        dest: /usr/local/bin/pebble
        mode: '0755'
        owner: root
        group: root
        url: https://github.com/letsencrypt/pebble/releases/download/{{ pebble_version }}/pebble_linux-amd64
      become: true

    - name: Create config directory
      file:
        path: /usr/local/etc/test/config
        state: directory
        mode: '0755'
        owner: root
        group: root
      become: true

    - name: Configure pebble
      template:
        dest: /usr/local/etc/test/config/pebble-config.json
        mode: '0644'
        owner: root
        group: root
        src: pebble-config.json.j2
      become: true
