---

roles:
  - name: uclalib_role_postgresql-legacy
    src: https://github.com/UCLALibrary/uclalib_role_postgresql.git
    scm: git
    version: 9f377997c037d9ec661daeed541c1cf5512102d1
    # HEAD as of 2021-08-25

  - name: uclalib_role_certbot
    src: https://github.com/UCLALibrary/uclalib_role_certbot.git
    scm: git
    version: bc1994ba1a04e5ce926e6c13d267d621f2174079
    # HEAD as of 2021-08-25
